### ISSUE TITLE
ERROR: Couldn't find env file:

### ISSUE THREAD

**Issue by nasirudin-me** [app-generator/flask-dashboard-adminator#1]
https://github.com/app-generator/flask-dashboard-adminator/blob/3d7b1c5ebcde93b648e53d4d11ea364e380d21e5/Dockerfile#L5

please help
i cant build with docker compose with error : ERROR: Couldn't find env file:
![Screenshot_4333](https://user-images.githubusercontent.com/9456293/86349676-bae0eb80-bc8b-11ea-85f7-4837f1cc3ecd.jpg)

**Comment by app-generator** [comment]
Hello, 
The Issue is now patched. Please update. 
Note - the app will be soon migrated to the latest [codebase](https://github.com/app-generator/boilerplate-code-flask-dashboard). 
FYI, we are using a unified codebase across all Flask Dashboards, generated by the service. 
For more information, please access: 
- AppSeed [Boilerplate Code](https://appseed.us/boilerplate-code) page
- [Discord](https://discord.com/invite/fZC6hup) LIVE support server
